
services:
  # Backend
  backend:
    build: ./Backend
    container_name: backend_container
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app-network

  # Frontend
  frontend:
    build: ./Frontend
    container_name: frontend_container
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  # Base de données PostgreSQL
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres_data:

